apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-sevice
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - app.tedxchulalongkornu.net
      secretName: tedxapp-net
  rules:
    - host: app.tedxchulalongkornu.net
      http:
        paths:
          - path: /
            backend:
              serviceName: nodejs
              servicePort: 3000
          - path: /db
            backend:
              serviceName: mongoexpress
              servicePort: 8081
   - host: db.tedxchulalongkornu.net
      http:
        paths:
          - path: /
            backend:
              serviceName: mongoexpress
              servicePort: 8081
